- name: update ubuntu machines
  apt: 
    update_cache: yes
  when: ansible_os_family == "Debian"
- name: update redhat machines
  yum:
    name: '*'
    update_cache: yes
    state: present
  when: ansible_os_family == "RedHat"
  
